### ISSUE TITLE
get_version method

### ISSUE THREAD

**Issue by fecetrulo** [iorust/jsonrpc-lite#7]
Hello, great crate.

I've found myself in a situation where i needed to compare the `jsonrpc` version and i couldn't do it without search on `json` itself. I would like to have a method to get the version from a `JsonRpc` `struct`.

it could be something like this:
```rust
pub fn get_version(&self) -> Option<&str> {
    match self {
        JsonRpc::Notification(ref v) => Some(&v.jsonrpc),
        JsonRpc::Request(ref v) => Some(&v.jsonrpc),
        JsonRpc::Success(ref v) => Some(&v.jsonrpc),
        JsonRpc::Error(ref v) => Some(&v.jsonrpc),
    }
}
```

**Comment by zensh** [comment]
Sorry for my delayed
